# This file was generated by GoReleaser. DO NOT EDIT.
cask "graft" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "94dff90fc27c844b2f752b9c636670163d616976e24e11ec82946c0216026cc8"
      url "https://github.com/optioni/graft/releases/download/v#{version}/graft_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7cd0400dd127b79df033a44628d58dbc30df609bed9af1f300c22e339797f4f"
      url "https://github.com/optioni/graft/releases/download/v#{version}/graft_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7e3d720b7a68566fe03e7e1a99d45d467426d6d881fab21aea9e0b13a0a8be31"
      url "https://github.com/optioni/graft/releases/download/v#{version}/graft_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0d30477b0e4f0b8c5a1bdd504c4ab22abe1f2c65e06285847e697ec953176f3"
      url "https://github.com/optioni/graft/releases/download/v#{version}/graft_#{version}_linux_amd64.tar.gz"
    end
  end

  name "graft"
  desc "Vendor files from a git repository into the repository you are standing in"
  homepage "https://github.com/optioni/graft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graft"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/graft"]
    end
  end

  # No zap stanza required
end
